"""add id PK to Pincodes Table

Revision ID: 100f66362d1a
Revises: 26a9abb1acf9
Create Date: 2021-05-31 16:44:40.217140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100f66362d1a'
down_revision = '26a9abb1acf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriber_pincode_preference_subscriber_id_postal_index_pr_key', 'subscriber_pincode_preferences', type_='unique')
    op.drop_constraint('subscriber_pincode_preferences_postal_index_fkey', 'subscriber_pincode_preferences', type_='foreignkey')
    op.drop_column('subscriber_pincode_preferences', 'postal_index')

    op.add_column('pincodes', sa.Column('id', sa.Integer(), nullable=False, unique=True))
    op.create_unique_constraint(None, 'pincodes', ['pincode'])
    op.add_column('subscriber_pincode_preferences', sa.Column('pincode_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'subscriber_pincode_preferences', ['subscriber_id', 'pincode_id', 'preference_id'])
    op.create_foreign_key(None, 'subscriber_pincode_preferences', 'pincodes', ['pincode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber_pincode_preferences', sa.Column('postal_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriber_pincode_preferences', type_='foreignkey')
    op.create_foreign_key('subscriber_pincode_preferences_postal_index_fkey', 'subscriber_pincode_preferences', 'pincodes', ['postal_index'], ['pincode'])
    op.drop_constraint(None, 'subscriber_pincode_preferences', type_='unique')
    op.create_unique_constraint('subscriber_pincode_preference_subscriber_id_postal_index_pr_key', 'subscriber_pincode_preferences', ['subscriber_id', 'postal_index', 'preference_id'])
    op.drop_column('subscriber_pincode_preferences', 'pincode_id')
    op.drop_constraint(None, 'pincodes', type_='unique')
    op.drop_column('pincodes', 'id')
    # ### end Alembic commands ###
