"""add separate columns for sub_18 & sub_45 mail sent datetime

Revision ID: 1e4c727afa67
Revises: e9144f3714bd
Create Date: 2021-05-18 19:29:22.707845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e4c727afa67'
down_revision = 'e9144f3714bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pincodes', sa.Column('sub_18_last_mail_sent_on', sa.DateTime(), nullable=True))
    op.add_column('pincodes', sa.Column('sub_45_last_mail_sent_on', sa.DateTime(), nullable=True))
    op.drop_column('pincodes', 'last_mail_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pincodes', sa.Column('last_mail_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pincodes', 'sub_45_last_mail_sent_on')
    op.drop_column('pincodes', 'sub_18_last_mail_sent_on')
    # ### end Alembic commands ###
