"""new normalized db models

Revision ID: 26a9abb1acf9
Revises: 1e4c727afa67
Create Date: 2021-05-30 23:11:06.116141

"""
import json

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26a9abb1acf9'
down_revision = '1e4c727afa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    preference_table = op.create_table('preference',
                                       sa.Column('id', sa.Integer(),
                                                 nullable=False),
                                       sa.Column(
                                           'sub_18', sa.Boolean(), nullable=False),
                                       sa.Column(
                                           'sub_45', sa.Boolean(), nullable=False),
                                       sa.PrimaryKeyConstraint('id')
                                       )
    op.create_table('subscriber_pincode_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subscriber_id', sa.Integer(), nullable=False),
                    sa.Column('postal_index', sa.Integer(), nullable=False),
                    sa.Column('preference_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['postal_index'], ['pincodes.pincode'], ),
                    sa.ForeignKeyConstraint(
                        ['preference_id'], ['preference.id'], ),
                    sa.ForeignKeyConstraint(
                        ['subscriber_id'], ['subscribers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'subscriber_id', 'postal_index', 'preference_id')
                    )
    op.drop_table('subscriber_pincode')
    op.create_unique_constraint(None, 'subscribers', ['phone'])
    op.create_unique_constraint(None, 'subscribers', ['email'])
    op.drop_column('subscribers', 'sub_18')
    op.drop_column('subscribers', 'sub_45')
    # ### end Alembic commands ###

    with open('migrations/seed_data/all_preferences.json', 'r') as preferences:
        op.bulk_insert(
            preference_table,
            json.load(preferences),
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column(
        'sub_45', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscribers', sa.Column(
        'sub_18', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.create_table('subscriber_pincode',
                    sa.Column('subscriber_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('pincode', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['pincode'], ['pincodes.pincode'], name='subscriber_pincode_pincode_fkey'),
                    sa.ForeignKeyConstraint(['subscriber_id'], [
                        'subscribers.id'], name='subscriber_pincode_subscriber_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'subscriber_id', 'pincode', name='subscriber_pincode_pkey')
                    )
    op.drop_table('subscriber_pincode_preferences')
    op.drop_table('preference')
    # ### end Alembic commands ###
