"""keep 1 column for name

Revision ID: c639b0b4157f
Revises: 7c5bf51f3716
Create Date: 2021-05-14 16:33:06.979980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c639b0b4157f'
down_revision = '7c5bf51f3716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('name', sa.String(length=64), nullable=False))
    op.drop_column('subscribers', 'first_name')
    op.drop_column('subscribers', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('subscribers', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('subscribers', 'name')
    # ### end Alembic commands ###
