"""3nf schema

Revision ID: d3e68f400290
Revises: 1e4c727afa67
Create Date: 2021-05-31 17:29:55.301065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e68f400290'
down_revision = '1e4c727afa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_pincode')
    op.drop_table('pincodes')
    op.drop_column('subscribers', 'sub_45')
    op.drop_column('subscribers', 'sub_18')

    op.create_unique_constraint(None, 'subscribers', ['email'])
    op.create_unique_constraint(None, 'subscribers', ['phone'])

    op.create_table('pincodes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pincode', sa.Integer(),
                              nullable=False, unique=True),
                    sa.Column('sub_18_last_mail_sent_on',
                              sa.DateTime(), nullable=True),
                    sa.Column('sub_18_last_mail_sent_on',
                              sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('preference',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sub_18', sa.Boolean(), nullable=False),
                    sa.Column('sub_45', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('subscriber_pincode_preferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subscriber_id', sa.Integer(), nullable=False),
                    sa.Column('pincode_id', sa.Integer(), nullable=False),
                    sa.Column('preference_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['pincode_id'], ['pincodes.id'], ),
                    sa.ForeignKeyConstraint(
                        ['preference_id'], ['preference.id'], ),
                    sa.ForeignKeyConstraint(
                        ['subscriber_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'subscriber_id', 'pincode_id', 'preference_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_constraint(None, 'subscribers', type_='unique')
    op.drop_constraint(None, 'pincodes', type_='unique')
    op.drop_column('pincodes', 'id')

    op.add_column('subscribers', sa.Column(
        'sub_18', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscribers', sa.Column(
        'sub_45', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.create_table('subscriber_pincode',
                    sa.Column('subscriber_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('pincode', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['pincode'], ['pincodes.pincode'], name='subscriber_pincode_pincode_fkey'),
                    sa.ForeignKeyConstraint(['subscriber_id'], [
                        'Users.id'], name='subscriber_pincode_subscriber_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'subscriber_id', 'pincode', name='subscriber_pincode_pkey')
                    )

    op.drop_table('subscriber_pincode_preferences')
    op.drop_table('preference')
    # ### end Alembic commands ###
