"""create seperate table for pincodes and build relationships

Revision ID: e9144f3714bd
Revises: c639b0b4157f
Create Date: 2021-05-16 21:19:32.505716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9144f3714bd'
down_revision = 'c639b0b4157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincodes',
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('last_mail_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_table('subscriber_pincode',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pincode'], ['pincodes.pincode'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'pincode')
    )
    op.add_column('subscribers', sa.Column('phone', sa.String(length=13), nullable=True))
    op.drop_column('subscribers', 'pincode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('pincode', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('subscribers', 'phone')
    op.drop_table('subscriber_pincode')
    op.drop_table('pincodes')
    # ### end Alembic commands ###
